### ISSUE TITLE
环境是PHP7.0，无法生成短地址

### ISSUE THREAD

**Issue by jeanbi** [Caringor/CRZ.im#1]
首先非常感谢开源这个功能，目前我使用碰到问题，烦请指教。

http://114.re

暂时未增加https，目前直接项目更新下来运行，都按照要求操作了，但是生成地址的时候显示undefined，还需要配置什么吗？

PHP7.0.18+Nginx 1.11.13

**Comment by Caringor** [comment]
检查一下 Nginx 关于 PHP 的配置是不是出什么问题了？
我看到 API 里面的 PHP 压根没有被解析哦。

**Comment by jeanbi** [comment]
好奇怪，info.php可以正常解析，就那个文件不行。

**Comment by jeanbi** [comment]
解决了，配置文件里不能加
```
location ^~ /api/ {
        root /var/www/CRZ.im;
}
```
至少，在我的环境里不能加这个。

**Comment by Caringor** [comment]
和你其它配置衝突了吧…
